add_newline = true

palette = "tokyonight"

format = """
$os$username$directory$git_branch$git_status$nodejs$java$kotlin$rust$cmd_duration
$character
"""

[palettes.tokyonight]
bg      = "#1a1b26"
fg      = "#c0caf5"
muted   = "#565f89"
blue    = "#7aa2f7"
cyan    = "#7dcfff"
green   = "#9ece6a"
yellow  = "#e0af68"
purple  = "#bb9af7"
red     = "#f7768e"

[os]
disabled = false
style = "bold blue"
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bold fg"
style_root = "bold red"
format = "[$user ]($style)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1
read_only = " "
format = "[$path]($style)[$read_only](red) "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Pictures" = "󰉏 "
"Projects" = "󰲋 "
"Code" = "󰆍 "

[git_branch]
symbol = "󰘬 "
style = "bold green"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style)) "

[nodejs]
symbol = " "
style = "purple"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "red"
format = "[$symbol$version]($style) "

[kotlin]
symbol = " "
style = "blue"
format = "[$symbol$version]($style) "

[rust]
symbol = "󱘗 "
style = "yellow"
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 1500
style = "muted"
format = "[󱦟 $duration]($style) "

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
